FROM arm64v8/node:20-bullseye
ENV NODE_ENV production

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    libcurl4-openssl-dev \
    openssl \
    && rm -rf /var/lib/apt/lists/*

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY [".env", "/usr/src/app"]
COPY . .

RUN cd /usr/src/app

RUN npm install

CMD ["node", "dist/src/index.js"]