FROM arm64v8/node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY data ./data
COPY .env ./
RUN npm install
COPY . .
RUN npm run build

FROM arm64v8/node:20-alpine
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/.env ./.env
COPY --from=builder /app/data/token.json ./data/token.json
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

CMD ["node", "dist/src/index.js"]